/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mydocker.ui.internal.MydockerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDockerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MydockerActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MydockerActivator activator = MydockerActivator.getInstance();
		return activator != null ? activator.getInjector(MydockerActivator.ORG_XTEXT_EXAMPLE_MYDOCKER_MYDOCKER) : null;
	}

}
