/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.myDocker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expose Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort <em>Port</em>}</li>
 *   <li>{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort_protocol <em>Port protocol</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getExposeArg()
 * @model
 * @generated
 */
public interface ExposeArg extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getExposeArg_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Port protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port protocol</em>' attribute.
   * @see #setPort_protocol(String)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getExposeArg_Port_protocol()
   * @model
   * @generated
   */
  String getPort_protocol();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort_protocol <em>Port protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port protocol</em>' attribute.
   * @see #getPort_protocol()
   * @generated
   */
  void setPort_protocol(String value);

} // ExposeArg
