/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.myDocker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Health Args</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydocker.myDocker.HealthArgs#getTyp <em>Typ</em>}</li>
 *   <li>{@link org.xtext.example.mydocker.myDocker.HealthArgs#getOptions <em>Options</em>}</li>
 *   <li>{@link org.xtext.example.mydocker.myDocker.HealthArgs#getCmdArgs <em>Cmd Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getHealthArgs()
 * @model
 * @generated
 */
public interface HealthArgs extends EObject
{
  /**
   * Returns the value of the '<em><b>Typ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typ</em>' attribute.
   * @see #setTyp(String)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getHealthArgs_Typ()
   * @model
   * @generated
   */
  String getTyp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getTyp <em>Typ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typ</em>' attribute.
   * @see #getTyp()
   * @generated
   */
  void setTyp(String value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference.
   * @see #setOptions(Options)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getHealthArgs_Options()
   * @model containment="true"
   * @generated
   */
  Options getOptions();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getOptions <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Options</em>' containment reference.
   * @see #getOptions()
   * @generated
   */
  void setOptions(Options value);

  /**
   * Returns the value of the '<em><b>Cmd Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd Args</em>' containment reference.
   * @see #setCmdArgs(CommandArgs)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getHealthArgs_CmdArgs()
   * @model containment="true"
   * @generated
   */
  CommandArgs getCmdArgs();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getCmdArgs <em>Cmd Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd Args</em>' containment reference.
   * @see #getCmdArgs()
   * @generated
   */
  void setCmdArgs(CommandArgs value);

} // HealthArgs
