/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.myDocker;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydocker.myDocker.MyDockerPackage
 * @generated
 */
public interface MyDockerFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDockerFactory eINSTANCE = org.xtext.example.mydocker.myDocker.impl.MyDockerFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Docker</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Docker</em>'.
   * @generated
   */
  Docker createDocker();

  /**
   * Returns a new object of class '<em>Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command</em>'.
   * @generated
   */
  Command createCommand();

  /**
   * Returns a new object of class '<em>Add</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add</em>'.
   * @generated
   */
  Add createAdd();

  /**
   * Returns a new object of class '<em>Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arg</em>'.
   * @generated
   */
  Arg createArg();

  /**
   * Returns a new object of class '<em>Cmd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cmd</em>'.
   * @generated
   */
  Cmd createCmd();

  /**
   * Returns a new object of class '<em>Copy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy</em>'.
   * @generated
   */
  Copy createCopy();

  /**
   * Returns a new object of class '<em>Entrypoint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entrypoint</em>'.
   * @generated
   */
  Entrypoint createEntrypoint();

  /**
   * Returns a new object of class '<em>Env</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Env</em>'.
   * @generated
   */
  Env createEnv();

  /**
   * Returns a new object of class '<em>Expose</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expose</em>'.
   * @generated
   */
  Expose createExpose();

  /**
   * Returns a new object of class '<em>From</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>From</em>'.
   * @generated
   */
  From createFrom();

  /**
   * Returns a new object of class '<em>Healthcheck</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Healthcheck</em>'.
   * @generated
   */
  Healthcheck createHealthcheck();

  /**
   * Returns a new object of class '<em>Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label</em>'.
   * @generated
   */
  Label createLabel();

  /**
   * Returns a new object of class '<em>Maintainer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Maintainer</em>'.
   * @generated
   */
  Maintainer createMaintainer();

  /**
   * Returns a new object of class '<em>Onbuild</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Onbuild</em>'.
   * @generated
   */
  Onbuild createOnbuild();

  /**
   * Returns a new object of class '<em>Run</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Run</em>'.
   * @generated
   */
  Run createRun();

  /**
   * Returns a new object of class '<em>Shell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shell</em>'.
   * @generated
   */
  Shell createShell();

  /**
   * Returns a new object of class '<em>Stop Signal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stop Signal</em>'.
   * @generated
   */
  StopSignal createStopSignal();

  /**
   * Returns a new object of class '<em>User</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User</em>'.
   * @generated
   */
  User createUser();

  /**
   * Returns a new object of class '<em>Volume</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Volume</em>'.
   * @generated
   */
  Volume createVolume();

  /**
   * Returns a new object of class '<em>Workdir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workdir</em>'.
   * @generated
   */
  Workdir createWorkdir();

  /**
   * Returns a new object of class '<em>Command Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Args</em>'.
   * @generated
   */
  CommandArgs createCommandArgs();

  /**
   * Returns a new object of class '<em>JSON Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JSON Args</em>'.
   * @generated
   */
  JSONArgs createJSONArgs();

  /**
   * Returns a new object of class '<em>Name Vals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name Vals</em>'.
   * @generated
   */
  NameVals createNameVals();

  /**
   * Returns a new object of class '<em>Name Val</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name Val</em>'.
   * @generated
   */
  NameVal createNameVal();

  /**
   * Returns a new object of class '<em>Arg Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arg Args</em>'.
   * @generated
   */
  ArgArgs createArgArgs();

  /**
   * Returns a new object of class '<em>Health Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Health Args</em>'.
   * @generated
   */
  HealthArgs createHealthArgs();

  /**
   * Returns a new object of class '<em>Options</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Options</em>'.
   * @generated
   */
  Options createOptions();

  /**
   * Returns a new object of class '<em>Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option</em>'.
   * @generated
   */
  Option createOption();

  /**
   * Returns a new object of class '<em>Expose Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expose Args</em>'.
   * @generated
   */
  ExposeArgs createExposeArgs();

  /**
   * Returns a new object of class '<em>Expose Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expose Arg</em>'.
   * @generated
   */
  ExposeArg createExposeArg();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDockerPackage getMyDockerPackage();

} //MyDockerFactory
