/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.myDocker;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydocker.myDocker.MyDockerFactory
 * @model kind="package"
 * @generated
 */
public interface MyDockerPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDocker";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydocker/MyDocker";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDocker";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDockerPackage eINSTANCE = org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.DockerImpl <em>Docker</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.DockerImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getDocker()
   * @generated
   */
  int DOCKER = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCKER__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Docker</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCKER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.CommandImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__CMD = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.AddImpl <em>Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.AddImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getAdd()
   * @generated
   */
  int ADD = 2;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ArgImpl <em>Arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ArgImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getArg()
   * @generated
   */
  int ARG = 3;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.CmdImpl <em>Cmd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.CmdImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCmd()
   * @generated
   */
  int CMD = 4;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cmd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.CopyImpl <em>Copy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.CopyImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCopy()
   * @generated
   */
  int COPY = 5;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Copy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPY_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.EntrypointImpl <em>Entrypoint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.EntrypointImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getEntrypoint()
   * @generated
   */
  int ENTRYPOINT = 6;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRYPOINT__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRYPOINT__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entrypoint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRYPOINT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.EnvImpl <em>Env</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.EnvImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getEnv()
   * @generated
   */
  int ENV = 7;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENV__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENV__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Env</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENV_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeImpl <em>Expose</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ExposeImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExpose()
   * @generated
   */
  int EXPOSE = 8;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expose</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.FromImpl <em>From</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.FromImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getFrom()
   * @generated
   */
  int FROM = 9;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>From</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.HealthcheckImpl <em>Healthcheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.HealthcheckImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getHealthcheck()
   * @generated
   */
  int HEALTHCHECK = 10;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTHCHECK__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTHCHECK__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Healthcheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTHCHECK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.LabelImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 11;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.MaintainerImpl <em>Maintainer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.MaintainerImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getMaintainer()
   * @generated
   */
  int MAINTAINER = 12;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINTAINER__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINTAINER__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Maintainer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAINTAINER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.OnbuildImpl <em>Onbuild</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.OnbuildImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOnbuild()
   * @generated
   */
  int ONBUILD = 13;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONBUILD__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONBUILD__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Onbuild</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONBUILD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.RunImpl <em>Run</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.RunImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getRun()
   * @generated
   */
  int RUN = 14;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Run</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ShellImpl <em>Shell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ShellImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getShell()
   * @generated
   */
  int SHELL = 15;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELL__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELL__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Shell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.StopSignalImpl <em>Stop Signal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.StopSignalImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getStopSignal()
   * @generated
   */
  int STOP_SIGNAL = 16;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_SIGNAL__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_SIGNAL__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Stop Signal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_SIGNAL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.UserImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getUser()
   * @generated
   */
  int USER = 17;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.VolumeImpl <em>Volume</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.VolumeImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getVolume()
   * @generated
   */
  int VOLUME = 18;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOLUME__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOLUME__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Volume</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOLUME_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.WorkdirImpl <em>Workdir</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.WorkdirImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getWorkdir()
   * @generated
   */
  int WORKDIR = 19;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKDIR__CMD = COMMAND__CMD;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKDIR__ARGS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Workdir</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKDIR_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.CommandArgsImpl <em>Command Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.CommandArgsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCommandArgs()
   * @generated
   */
  int COMMAND_ARGS = 20;

  /**
   * The number of structural features of the '<em>Command Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_ARGS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.JSONArgsImpl <em>JSON Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.JSONArgsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getJSONArgs()
   * @generated
   */
  int JSON_ARGS = 21;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARGS__ARGS = COMMAND_ARGS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>JSON Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARGS_FEATURE_COUNT = COMMAND_ARGS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.NameValsImpl <em>Name Vals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.NameValsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getNameVals()
   * @generated
   */
  int NAME_VALS = 22;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_VALS__VALUES = 0;

  /**
   * The number of structural features of the '<em>Name Vals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_VALS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.NameValImpl <em>Name Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.NameValImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getNameVal()
   * @generated
   */
  int NAME_VAL = 23;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_VAL__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_VAL__VALUE = 1;

  /**
   * The number of structural features of the '<em>Name Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_VAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ArgArgsImpl <em>Arg Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ArgArgsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getArgArgs()
   * @generated
   */
  int ARG_ARGS = 24;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_ARGS__VALUE = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_ARGS__VALUES = 1;

  /**
   * The number of structural features of the '<em>Arg Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_ARGS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.HealthArgsImpl <em>Health Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.HealthArgsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getHealthArgs()
   * @generated
   */
  int HEALTH_ARGS = 25;

  /**
   * The feature id for the '<em><b>Typ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_ARGS__TYP = 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_ARGS__OPTIONS = 1;

  /**
   * The feature id for the '<em><b>Cmd Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_ARGS__CMD_ARGS = 2;

  /**
   * The number of structural features of the '<em>Health Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_ARGS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.OptionsImpl <em>Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.OptionsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOptions()
   * @generated
   */
  int OPTIONS = 26;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONS__OPTIONS = 0;

  /**
   * The number of structural features of the '<em>Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.OptionImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOption()
   * @generated
   */
  int OPTION = 27;

  /**
   * The feature id for the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__OPTION = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeArgsImpl <em>Expose Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ExposeArgsImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExposeArgs()
   * @generated
   */
  int EXPOSE_ARGS = 28;

  /**
   * The feature id for the '<em><b>Ports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_ARGS__PORTS = 0;

  /**
   * The number of structural features of the '<em>Expose Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_ARGS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeArgImpl <em>Expose Arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydocker.myDocker.impl.ExposeArgImpl
   * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExposeArg()
   * @generated
   */
  int EXPOSE_ARG = 29;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_ARG__PORT = 0;

  /**
   * The feature id for the '<em><b>Port protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_ARG__PORT_PROTOCOL = 1;

  /**
   * The number of structural features of the '<em>Expose Arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPOSE_ARG_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Docker <em>Docker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Docker</em>'.
   * @see org.xtext.example.mydocker.myDocker.Docker
   * @generated
   */
  EClass getDocker();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydocker.myDocker.Docker#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.mydocker.myDocker.Docker#getCommands()
   * @see #getDocker()
   * @generated
   */
  EReference getDocker_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.mydocker.myDocker.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Command#getCmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cmd</em>'.
   * @see org.xtext.example.mydocker.myDocker.Command#getCmd()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Cmd();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Add <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add</em>'.
   * @see org.xtext.example.mydocker.myDocker.Add
   * @generated
   */
  EClass getAdd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Add#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Add#getArgs()
   * @see #getAdd()
   * @generated
   */
  EReference getAdd_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Arg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arg</em>'.
   * @see org.xtext.example.mydocker.myDocker.Arg
   * @generated
   */
  EClass getArg();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Arg#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Arg#getArgs()
   * @see #getArg()
   * @generated
   */
  EReference getArg_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Cmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cmd</em>'.
   * @see org.xtext.example.mydocker.myDocker.Cmd
   * @generated
   */
  EClass getCmd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Cmd#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Cmd#getArgs()
   * @see #getCmd()
   * @generated
   */
  EReference getCmd_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Copy <em>Copy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Copy</em>'.
   * @see org.xtext.example.mydocker.myDocker.Copy
   * @generated
   */
  EClass getCopy();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Copy#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Copy#getArgs()
   * @see #getCopy()
   * @generated
   */
  EReference getCopy_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Entrypoint <em>Entrypoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entrypoint</em>'.
   * @see org.xtext.example.mydocker.myDocker.Entrypoint
   * @generated
   */
  EClass getEntrypoint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Entrypoint#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Entrypoint#getArgs()
   * @see #getEntrypoint()
   * @generated
   */
  EReference getEntrypoint_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Env <em>Env</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Env</em>'.
   * @see org.xtext.example.mydocker.myDocker.Env
   * @generated
   */
  EClass getEnv();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Env#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Env#getArgs()
   * @see #getEnv()
   * @generated
   */
  EReference getEnv_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Expose <em>Expose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expose</em>'.
   * @see org.xtext.example.mydocker.myDocker.Expose
   * @generated
   */
  EClass getExpose();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Expose#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Expose#getArgs()
   * @see #getExpose()
   * @generated
   */
  EReference getExpose_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.From <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>From</em>'.
   * @see org.xtext.example.mydocker.myDocker.From
   * @generated
   */
  EClass getFrom();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.From#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.From#getArgs()
   * @see #getFrom()
   * @generated
   */
  EReference getFrom_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Healthcheck <em>Healthcheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Healthcheck</em>'.
   * @see org.xtext.example.mydocker.myDocker.Healthcheck
   * @generated
   */
  EClass getHealthcheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Healthcheck#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Healthcheck#getArgs()
   * @see #getHealthcheck()
   * @generated
   */
  EReference getHealthcheck_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.xtext.example.mydocker.myDocker.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Label#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Label#getArgs()
   * @see #getLabel()
   * @generated
   */
  EReference getLabel_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Maintainer <em>Maintainer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maintainer</em>'.
   * @see org.xtext.example.mydocker.myDocker.Maintainer
   * @generated
   */
  EClass getMaintainer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Maintainer#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Maintainer#getArgs()
   * @see #getMaintainer()
   * @generated
   */
  EAttribute getMaintainer_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Onbuild <em>Onbuild</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Onbuild</em>'.
   * @see org.xtext.example.mydocker.myDocker.Onbuild
   * @generated
   */
  EClass getOnbuild();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Onbuild#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Onbuild#getArgs()
   * @see #getOnbuild()
   * @generated
   */
  EAttribute getOnbuild_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Run <em>Run</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Run</em>'.
   * @see org.xtext.example.mydocker.myDocker.Run
   * @generated
   */
  EClass getRun();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Run#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Run#getArgs()
   * @see #getRun()
   * @generated
   */
  EReference getRun_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Shell <em>Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shell</em>'.
   * @see org.xtext.example.mydocker.myDocker.Shell
   * @generated
   */
  EClass getShell();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Shell#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Shell#getArgs()
   * @see #getShell()
   * @generated
   */
  EReference getShell_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.StopSignal <em>Stop Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop Signal</em>'.
   * @see org.xtext.example.mydocker.myDocker.StopSignal
   * @generated
   */
  EClass getStopSignal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.StopSignal#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.StopSignal#getArgs()
   * @see #getStopSignal()
   * @generated
   */
  EAttribute getStopSignal_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see org.xtext.example.mydocker.myDocker.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.User#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.User#getArgs()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Volume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Volume</em>'.
   * @see org.xtext.example.mydocker.myDocker.Volume
   * @generated
   */
  EClass getVolume();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.Volume#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Volume#getArgs()
   * @see #getVolume()
   * @generated
   */
  EReference getVolume_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Workdir <em>Workdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workdir</em>'.
   * @see org.xtext.example.mydocker.myDocker.Workdir
   * @generated
   */
  EClass getWorkdir();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Workdir#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.Workdir#getArgs()
   * @see #getWorkdir()
   * @generated
   */
  EAttribute getWorkdir_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.CommandArgs <em>Command Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.CommandArgs
   * @generated
   */
  EClass getCommandArgs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.JSONArgs <em>JSON Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.JSONArgs
   * @generated
   */
  EClass getJSONArgs();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydocker.myDocker.JSONArgs#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.JSONArgs#getArgs()
   * @see #getJSONArgs()
   * @generated
   */
  EAttribute getJSONArgs_Args();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.NameVals <em>Name Vals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Name Vals</em>'.
   * @see org.xtext.example.mydocker.myDocker.NameVals
   * @generated
   */
  EClass getNameVals();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydocker.myDocker.NameVals#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.xtext.example.mydocker.myDocker.NameVals#getValues()
   * @see #getNameVals()
   * @generated
   */
  EReference getNameVals_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.NameVal <em>Name Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Name Val</em>'.
   * @see org.xtext.example.mydocker.myDocker.NameVal
   * @generated
   */
  EClass getNameVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.NameVal#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.mydocker.myDocker.NameVal#getKey()
   * @see #getNameVal()
   * @generated
   */
  EAttribute getNameVal_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.NameVal#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydocker.myDocker.NameVal#getValue()
   * @see #getNameVal()
   * @generated
   */
  EAttribute getNameVal_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.ArgArgs <em>Arg Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arg Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.ArgArgs
   * @generated
   */
  EClass getArgArgs();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.ArgArgs#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydocker.myDocker.ArgArgs#getValue()
   * @see #getArgArgs()
   * @generated
   */
  EAttribute getArgArgs_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.ArgArgs#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Values</em>'.
   * @see org.xtext.example.mydocker.myDocker.ArgArgs#getValues()
   * @see #getArgArgs()
   * @generated
   */
  EReference getArgArgs_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.HealthArgs <em>Health Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Health Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.HealthArgs
   * @generated
   */
  EClass getHealthArgs();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getTyp <em>Typ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Typ</em>'.
   * @see org.xtext.example.mydocker.myDocker.HealthArgs#getTyp()
   * @see #getHealthArgs()
   * @generated
   */
  EAttribute getHealthArgs_Typ();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Options</em>'.
   * @see org.xtext.example.mydocker.myDocker.HealthArgs#getOptions()
   * @see #getHealthArgs()
   * @generated
   */
  EReference getHealthArgs_Options();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydocker.myDocker.HealthArgs#getCmdArgs <em>Cmd Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.HealthArgs#getCmdArgs()
   * @see #getHealthArgs()
   * @generated
   */
  EReference getHealthArgs_CmdArgs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Options <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Options</em>'.
   * @see org.xtext.example.mydocker.myDocker.Options
   * @generated
   */
  EClass getOptions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydocker.myDocker.Options#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see org.xtext.example.mydocker.myDocker.Options#getOptions()
   * @see #getOptions()
   * @generated
   */
  EReference getOptions_Options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see org.xtext.example.mydocker.myDocker.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Option#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option</em>'.
   * @see org.xtext.example.mydocker.myDocker.Option#getOption()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Option();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.Option#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydocker.myDocker.Option#getValue()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.ExposeArgs <em>Expose Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expose Args</em>'.
   * @see org.xtext.example.mydocker.myDocker.ExposeArgs
   * @generated
   */
  EClass getExposeArgs();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydocker.myDocker.ExposeArgs#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ports</em>'.
   * @see org.xtext.example.mydocker.myDocker.ExposeArgs#getPorts()
   * @see #getExposeArgs()
   * @generated
   */
  EReference getExposeArgs_Ports();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydocker.myDocker.ExposeArg <em>Expose Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expose Arg</em>'.
   * @see org.xtext.example.mydocker.myDocker.ExposeArg
   * @generated
   */
  EClass getExposeArg();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.xtext.example.mydocker.myDocker.ExposeArg#getPort()
   * @see #getExposeArg()
   * @generated
   */
  EAttribute getExposeArg_Port();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydocker.myDocker.ExposeArg#getPort_protocol <em>Port protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port protocol</em>'.
   * @see org.xtext.example.mydocker.myDocker.ExposeArg#getPort_protocol()
   * @see #getExposeArg()
   * @generated
   */
  EAttribute getExposeArg_Port_protocol();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDockerFactory getMyDockerFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.DockerImpl <em>Docker</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.DockerImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getDocker()
     * @generated
     */
    EClass DOCKER = eINSTANCE.getDocker();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCKER__COMMANDS = eINSTANCE.getDocker_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.CommandImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Cmd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__CMD = eINSTANCE.getCommand_Cmd();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.AddImpl <em>Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.AddImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getAdd()
     * @generated
     */
    EClass ADD = eINSTANCE.getAdd();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__ARGS = eINSTANCE.getAdd_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ArgImpl <em>Arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ArgImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getArg()
     * @generated
     */
    EClass ARG = eINSTANCE.getArg();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARG__ARGS = eINSTANCE.getArg_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.CmdImpl <em>Cmd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.CmdImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCmd()
     * @generated
     */
    EClass CMD = eINSTANCE.getCmd();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMD__ARGS = eINSTANCE.getCmd_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.CopyImpl <em>Copy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.CopyImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCopy()
     * @generated
     */
    EClass COPY = eINSTANCE.getCopy();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COPY__ARGS = eINSTANCE.getCopy_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.EntrypointImpl <em>Entrypoint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.EntrypointImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getEntrypoint()
     * @generated
     */
    EClass ENTRYPOINT = eINSTANCE.getEntrypoint();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRYPOINT__ARGS = eINSTANCE.getEntrypoint_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.EnvImpl <em>Env</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.EnvImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getEnv()
     * @generated
     */
    EClass ENV = eINSTANCE.getEnv();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENV__ARGS = eINSTANCE.getEnv_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeImpl <em>Expose</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ExposeImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExpose()
     * @generated
     */
    EClass EXPOSE = eINSTANCE.getExpose();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPOSE__ARGS = eINSTANCE.getExpose_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.FromImpl <em>From</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.FromImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getFrom()
     * @generated
     */
    EClass FROM = eINSTANCE.getFrom();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM__ARGS = eINSTANCE.getFrom_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.HealthcheckImpl <em>Healthcheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.HealthcheckImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getHealthcheck()
     * @generated
     */
    EClass HEALTHCHECK = eINSTANCE.getHealthcheck();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEALTHCHECK__ARGS = eINSTANCE.getHealthcheck_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.LabelImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL__ARGS = eINSTANCE.getLabel_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.MaintainerImpl <em>Maintainer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.MaintainerImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getMaintainer()
     * @generated
     */
    EClass MAINTAINER = eINSTANCE.getMaintainer();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAINTAINER__ARGS = eINSTANCE.getMaintainer_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.OnbuildImpl <em>Onbuild</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.OnbuildImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOnbuild()
     * @generated
     */
    EClass ONBUILD = eINSTANCE.getOnbuild();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ONBUILD__ARGS = eINSTANCE.getOnbuild_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.RunImpl <em>Run</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.RunImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getRun()
     * @generated
     */
    EClass RUN = eINSTANCE.getRun();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RUN__ARGS = eINSTANCE.getRun_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ShellImpl <em>Shell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ShellImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getShell()
     * @generated
     */
    EClass SHELL = eINSTANCE.getShell();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHELL__ARGS = eINSTANCE.getShell_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.StopSignalImpl <em>Stop Signal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.StopSignalImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getStopSignal()
     * @generated
     */
    EClass STOP_SIGNAL = eINSTANCE.getStopSignal();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP_SIGNAL__ARGS = eINSTANCE.getStopSignal_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.UserImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__ARGS = eINSTANCE.getUser_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.VolumeImpl <em>Volume</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.VolumeImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getVolume()
     * @generated
     */
    EClass VOLUME = eINSTANCE.getVolume();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOLUME__ARGS = eINSTANCE.getVolume_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.WorkdirImpl <em>Workdir</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.WorkdirImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getWorkdir()
     * @generated
     */
    EClass WORKDIR = eINSTANCE.getWorkdir();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKDIR__ARGS = eINSTANCE.getWorkdir_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.CommandArgsImpl <em>Command Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.CommandArgsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getCommandArgs()
     * @generated
     */
    EClass COMMAND_ARGS = eINSTANCE.getCommandArgs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.JSONArgsImpl <em>JSON Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.JSONArgsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getJSONArgs()
     * @generated
     */
    EClass JSON_ARGS = eINSTANCE.getJSONArgs();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_ARGS__ARGS = eINSTANCE.getJSONArgs_Args();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.NameValsImpl <em>Name Vals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.NameValsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getNameVals()
     * @generated
     */
    EClass NAME_VALS = eINSTANCE.getNameVals();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAME_VALS__VALUES = eINSTANCE.getNameVals_Values();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.NameValImpl <em>Name Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.NameValImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getNameVal()
     * @generated
     */
    EClass NAME_VAL = eINSTANCE.getNameVal();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAME_VAL__KEY = eINSTANCE.getNameVal_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAME_VAL__VALUE = eINSTANCE.getNameVal_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ArgArgsImpl <em>Arg Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ArgArgsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getArgArgs()
     * @generated
     */
    EClass ARG_ARGS = eINSTANCE.getArgArgs();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_ARGS__VALUE = eINSTANCE.getArgArgs_Value();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARG_ARGS__VALUES = eINSTANCE.getArgArgs_Values();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.HealthArgsImpl <em>Health Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.HealthArgsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getHealthArgs()
     * @generated
     */
    EClass HEALTH_ARGS = eINSTANCE.getHealthArgs();

    /**
     * The meta object literal for the '<em><b>Typ</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_ARGS__TYP = eINSTANCE.getHealthArgs_Typ();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEALTH_ARGS__OPTIONS = eINSTANCE.getHealthArgs_Options();

    /**
     * The meta object literal for the '<em><b>Cmd Args</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEALTH_ARGS__CMD_ARGS = eINSTANCE.getHealthArgs_CmdArgs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.OptionsImpl <em>Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.OptionsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOptions()
     * @generated
     */
    EClass OPTIONS = eINSTANCE.getOptions();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTIONS__OPTIONS = eINSTANCE.getOptions_Options();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.OptionImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__OPTION = eINSTANCE.getOption_Option();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__VALUE = eINSTANCE.getOption_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeArgsImpl <em>Expose Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ExposeArgsImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExposeArgs()
     * @generated
     */
    EClass EXPOSE_ARGS = eINSTANCE.getExposeArgs();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPOSE_ARGS__PORTS = eINSTANCE.getExposeArgs_Ports();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydocker.myDocker.impl.ExposeArgImpl <em>Expose Arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydocker.myDocker.impl.ExposeArgImpl
     * @see org.xtext.example.mydocker.myDocker.impl.MyDockerPackageImpl#getExposeArg()
     * @generated
     */
    EClass EXPOSE_ARG = eINSTANCE.getExposeArg();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPOSE_ARG__PORT = eINSTANCE.getExposeArg_Port();

    /**
     * The meta object literal for the '<em><b>Port protocol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPOSE_ARG__PORT_PROTOCOL = eINSTANCE.getExposeArg_Port_protocol();

  }

} //MyDockerPackage
