/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.myDocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stop Signal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydocker.myDocker.StopSignal#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getStopSignal()
 * @model
 * @generated
 */
public interface StopSignal extends Command
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' attribute.
   * @see #setArgs(String)
   * @see org.xtext.example.mydocker.myDocker.MyDockerPackage#getStopSignal_Args()
   * @model
   * @generated
   */
  String getArgs();

  /**
   * Sets the value of the '{@link org.xtext.example.mydocker.myDocker.StopSignal#getArgs <em>Args</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' attribute.
   * @see #getArgs()
   * @generated
   */
  void setArgs(String value);

} // StopSignal
