/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.ide;


/**
 * Use this class to register ide components.
 */
public class MyDockerIdeModule extends AbstractMyDockerIdeModule {
}
