/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyDockerValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.mydocker.myDocker.MyDockerPackage.eINSTANCE);
		return result;
	}
}
