/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MyDockerProposalProvider extends AbstractMyDockerProposalProvider {
}
