/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydocker.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDockerScopeProvider extends DelegatingScopeProvider {
}
